FROM python:3.11-slim

WORKDIR /app

COPY ./backend /app
COPY requirements.txt /app/requirements.txt

RUN pip install --no-cache-dir -r requirements.txt

CMD ["uvicorn", "llama_app:app", "--host", "0.0.0.0", "--port", "8000"]